apiVersion: v1
kind: ReplicationController
metadata:
  name: springbooktestclient
spec:
  replicas: 1
#  selector:
#    matchLabels:
#      app: springbooktestclient
  template:
    metadata:
      labels:
        app: springbooktestclient
#        role: springbooktestclient
    spec:
      containers:
      - name: springbooktestclient
        image: mricim/book_test_client:initial
        imagePullPolicy: Always
        ports:
          - containerPort: 8081
        env:
        - name: URL_SERVER_BOOKS
          value: "https://booksa.ericcm.tk"
#          valueFrom:
#           configMapKeyRef:
#             name: ingressroutetls3
#             key: host
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 8081
#            httpHeaders:
#            - name: X-Custom-Header
#              value: Awesome
#          initialDelaySeconds: 10
#          periodSeconds: 3
##          failureThreshold: 1
##Check ready container
#        readinessProbe:
#          httpGet:
#            path: /books/libraryp
#            port: 8081
##            httpHeaders:
##            - name: X-Custom-Header
##              value: Awesome
#          initialDelaySeconds: 6
#          periodSeconds: 5
#          successThreshold: 1
#          timeoutSeconds: 1
