apiVersion: v1
kind: ReplicationController
metadata:
  name: springbooktestserver
spec:
  replicas: 1
#  selector:
#    matchLabels:
#      app: springbooktestclient
  template:
    metadata:
      labels:
        app: springbooktestserver
#        role: springbooktestclient
    spec:
      containers:
      - name: springbooktestserver
        image: mricim/booktestserver:initial
        imagePullPolicy: Always
        ports:
          - containerPort: 8086
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 8081
#            httpHeaders:
#            - name: X-Custom-Header
#              value: Awesome
#          initialDelaySeconds: 10
#          periodSeconds: 3
##          failureThreshold: 1
##Check ready container
#        readinessProbe:
#          httpGet:
#            path: /books/libraryp
#            port: 8081
##            httpHeaders:
##            - name: X-Custom-Header
##              value: Awesome
#          initialDelaySeconds: 6
#          periodSeconds: 5
#          successThreshold: 1
#          timeoutSeconds: 1
